import { StrategyDef } from "../types";

const wd = (
  n: number,
  key: string,
  name: string,
  description: string,
  params: StrategyDef["params"]
): StrategyDef => ({
  id: `wd_${String(n).padStart(2, "0")}_${key}`,
  name,
  family: "wallet_discovery",
  description,
  params,
});

const prop = (
  n: number,
  key: string,
  name: string,
  description: string,
  params: StrategyDef["params"]
): StrategyDef => ({
  id: `prop_${String(n).padStart(2, "0")}_${key}`,
  name,
  family: "proprietary",
  description,
  params,
});

export const WALLET_STRATEGIES: StrategyDef[] = [
  wd(1, "month_pnl", "Month PnL Leaders", "Follow top monthly PnL wallets.", { window: "MONTH", orderBy: "PNL", topN: 5 }),
  wd(2, "week_pnl", "Week PnL Leaders", "Follow top weekly PnL wallets.", { window: "WEEK", orderBy: "PNL", topN: 5 }),
  wd(3, "day_pnl", "Day PnL Leaders", "Follow top daily PnL wallets.", { window: "DAY", orderBy: "PNL", topN: 3 }),
  wd(4, "all_pnl", "All-time PnL Leaders", "Follow all-time PnL leaders.", { window: "ALL", orderBy: "PNL", topN: 5 }),
  wd(5, "month_vol", "Month Volume Leaders", "Follow highest monthly volume.", { window: "MONTH", orderBy: "VOL", topN: 5 }),
  wd(6, "week_vol", "Week Volume Leaders", "Follow highest weekly volume.", { window: "WEEK", orderBy: "VOL", topN: 5 }),
  wd(7, "pnl_eff", "PnL Efficiency", "Rank by pnl/vol on monthly board.", { window: "MONTH", score: "pnl_over_vol", topN: 5 }),
  wd(8, "multi_window", "Multi-window Consistency", "On week AND month boards.", { require: "week_and_month", topN: 5 }),
  wd(9, "triple", "Triple Window", "On day, week, and month boards.", { require: "day_week_month", topN: 3 }),
  wd(10, "mid_tier", "Mid-tier PnL", "Monthly ranks 10–25.", { window: "MONTH", rankFrom: 10, rankTo: 25, topN: 5 }),
  wd(11, "small_book", "Smaller Book Alpha", "High PnL, capped volume.", { window: "MONTH", maxVol: 2000000, topN: 5 }),
  wd(12, "large_book", "Large Book Whales", "Min volume filter.", { window: "MONTH", minVol: 5000000, topN: 5 }),
  wd(13, "fade_day", "Fade Day Hot-Hands", "Invert day-leader sides.", { window: "DAY", mode: "invert_side", topN: 5 }),
  wd(14, "stable_all", "Stable All-time ∩ Month", "On all-time and month.", { require: "all_and_month", topN: 5 }),
  wd(15, "breakout", "Month Breakouts", "Strong month, not all-time top.", { mode: "month_not_alltime", topN: 5 }),
  wd(16, "climbers", "Climbers", "Week rank better than month rank.", { mode: "week_better_than_month", topN: 5 }),
  wd(17, "vol_stable", "Steady Volume", "Week+month volume presence via PnL boards.", { require: "week_and_month", orderBy: "VOL", topN: 5 }),
  wd(18, "retail_tier", "Capital-tier Match", "Prefer mid volume wallets.", { window: "MONTH", score: "retail_tier", topN: 5 }),
  wd(19, "ex_ultravol", "Exclude Ultra Volume", "Drop extreme vol names.", { window: "MONTH", maxVol: 20000000, topN: 5 }),
  wd(20, "balanced", "Balanced PnL+Vol", "Composite rank score.", { window: "MONTH", score: "balanced", topN: 5 }),
  wd(21, "week_special", "Week Specialists", "Strong week, not all-time.", { mode: "week_not_alltime", topN: 5 }),
  wd(22, "persist", "Persistence Score", "Appearances across windows.", { score: "persistence", topN: 5 }),
  wd(23, "risk_adj", "Risk-adjusted Proxy", "pnl/sqrt(vol).", { window: "MONTH", score: "pnl_sqrt_vol", topN: 5 }),
  wd(24, "top1", "Single Leader", "Only #1 monthly PnL.", { window: "MONTH", topN: 1 }),
  wd(25, "top3", "Top 3 Equal", "Top 3 monthly.", { window: "MONTH", topN: 3 }),
  wd(26, "top10_thin", "Top 10 Thin", "Top 10, smaller clips.", { window: "MONTH", topN: 10, sizeScale: 0.5 }),
  wd(27, "anti_lb", "Anti-Leaderboard", "Ranks 30–50 control.", { window: "MONTH", rankFrom: 30, rankTo: 50, topN: 5 }),
  wd(28, "fade_vol", "Fade Volume Leaders", "Invert high-price buys of vol leaders.", { window: "MONTH", orderBy: "VOL", mode: "fade_high_price", topN: 5 }),
  wd(29, "mid_conv", "High Conviction Mid", "Leaders only at 0.35–0.65.", { window: "MONTH", mode: "mid_price_only", topN: 5 }),
  wd(30, "exits", "Exit-Following", "Copy sells from leaders.", { window: "MONTH", mode: "sells_only", topN: 5 }),
  wd(31, "entries", "Entry-Following", "Copy buys from leaders.", { window: "MONTH", mode: "buys_only", topN: 5 }),
  wd(32, "consensus", "Cluster Consensus", "≥2 watched wallets same tape.", { window: "MONTH", mode: "consensus", topN: 8 }),
  wd(33, "fresh", "Lag-Filtered Copy", "Prefer freshest tape.", { window: "MONTH", mode: "fresh_only", topN: 5 }),
  wd(34, "sports", "Sports-title Follow", "Leaders on sports-like titles.", { window: "MONTH", categoryHint: "sports", topN: 5 }),
  wd(35, "crypto", "Crypto-title Follow", "Leaders on crypto titles.", { window: "MONTH", categoryHint: "crypto", topN: 5 }),
  wd(36, "politics", "Politics-title Follow", "Leaders on politics titles.", { window: "MONTH", categoryHint: "politics", topN: 5 }),
  wd(37, "quintiles", "Diversified 5", "One wallet per quintile.", { window: "MONTH", mode: "quintiles", topN: 5 }),
  wd(38, "rot_week", "Weekly Rotation", "Re-pick week board.", { window: "WEEK", topN: 5 }),
  wd(39, "rot_day", "Daily Rotation", "Re-pick day board.", { window: "DAY", topN: 3 }),
  wd(40, "pnl_floor", "PnL Floor", "Month pnl > 50k.", { window: "MONTH", minPnl: 50000, topN: 5 }),
  wd(41, "pnl_band", "PnL Band", "PnL between 10k–200k.", { window: "MONTH", minPnl: 10000, maxPnl: 200000, topN: 5 }),
  wd(42, "dual_top", "Dual Top", "PnL∩Vol leaders.", { require: "pnl_and_vol_top", topN: 5 }),
  wd(43, "second_wave", "Second Wave", "Ranks 6–15.", { window: "MONTH", rankFrom: 6, rankTo: 15, topN: 5 }),
  wd(44, "contrarian_day", "Contrarian Day", "Invert day leaders.", { window: "DAY", mode: "invert_side", topN: 5 }),
  wd(45, "mom_stack", "Momentum Stack", "Day+week, buys only.", { require: "day_and_week", mode: "buys_only", topN: 5 }),
  wd(46, "mr_stack", "Mean-reversion Stack", "Fade day leaders.", { window: "DAY", mode: "invert_side", topN: 5 }),
  wd(47, "quality_vol", "Quality Volume", "Vol leaders with pnl>0.", { window: "MONTH", orderBy: "VOL", minPnl: 1, topN: 5 }),
  wd(48, "sparse_elite", "Sparse Elite", "Top 2 all-time.", { window: "ALL", topN: 2 }),
  wd(49, "broad15", "Broad Watch 15", "15 monthly names, thin size.", { window: "MONTH", topN: 15, sizeScale: 0.4 }),
  wd(50, "hybrid", "Hybrid Week/Month", "Blend week + month leaders.", { mode: "blend_week_month", topN: 6 }),
  // CopyGrade shortlist — one bot per wallet @ $1k (fixedWallet pins the leader).
  wd(51, "cg_poppyg", "CopyGrade · PoppyG", "Mirror CopyGrade #1 PoppyG (score 95, clean).", {
    fixedWallet: "0x5b7fc994c653072b721669229ea2bed937065fea",
    handle: "PoppyG",
    mode: "buys_only",
    topN: 1,
  }),
  wd(52, "cg_phatsddds125", "CopyGrade · phatsddds125", "Mirror CopyGrade #2 phatsddds125 (score 94, clean).", {
    fixedWallet: "0x02787037f71640fd46b8f0d127b9d40e40a5bff4",
    handle: "phatsddds125",
    mode: "buys_only",
    topN: 1,
  }),
  wd(53, "cg_misty", "CopyGrade · Misty-Notoriety-Manager", "Mirror CopyGrade #3 Misty-Notoriety-Manager (score 94, clean).", {
    fixedWallet: "0xe9874755a61983acda6e51487d39314b1db087c8",
    handle: "Misty-Notoriety-Manager",
    mode: "buys_only",
    topN: 1,
  }),
  wd(54, "cg_ziiizar01", "CopyGrade · ziiizar01", "Mirror CopyGrade #4 ziiizar01 (score 93, clean).", {
    fixedWallet: "0xb9416f6ca813e46ed2f73071cca011663dac1619",
    handle: "ziiizar01",
    mode: "buys_only",
    topN: 1,
  }),
  wd(55, "cg_bubu12", "CopyGrade · BuBu12", "Mirror CopyGrade #5 BuBu12 (score 92, clean).", {
    fixedWallet: "0xea41ce13c290a4491f946b5976c79c901ff80782",
    handle: "BuBu12",
    mode: "buys_only",
    topN: 1,
  }),
];

export const PROP_STRATEGIES: StrategyDef[] = [
  prop(1, "fade_longshots", "Fade Longshots", "Fade YES buys priced as longshots.", { mode: "fade_longshot", longshot: 0.15 }),
  prop(2, "buy_favorites", "Buy Favorites", "Buy when price > 0.75.", { mode: "buy_favorite", favorite: 0.75 }),
  prop(3, "fade_ls_flip", "Longshot Flip", "Flip side on longshot prints.", { mode: "fade_longshot_flip", longshot: 0.12 }),
  prop(4, "mid_value", "Mid-price Value", "Only 0.40–0.60.", { mode: "mid_band", lo: 0.4, hi: 0.6 }),
  prop(5, "avoid_certain", "Avoid Near-Certain", "Skip extremes.", { mode: "skip_extreme", lo: 0.08, hi: 0.92 }),
  prop(6, "tape_mom", "Tape Momentum", "Follow buy tape.", { mode: "tape_momentum" }),
  prop(7, "tape_fade", "Tape Exhaustion Fade", "Fade tape bursts.", { mode: "tape_fade" }),
  prop(8, "size_follow", "Size Spike Follow", "Follow large size.", { mode: "size_spike", minSize: 500 }),
  prop(9, "size_fade", "Size Spike Fade", "Fade large size.", { mode: "size_spike_fade", minSize: 500 }),
  prop(10, "crypto_fade", "Crypto Up/Down Fade", "Fade short-horizon crypto.", { mode: "crypto_updown_fade" }),
  prop(11, "crypto_follow", "Crypto Up/Down Follow", "Follow crypto shorts.", { mode: "crypto_updown_follow" }),
  prop(12, "sports_buy", "Sports Buy Flow", "Sports buys.", { mode: "category_follow", categoryHint: "sports", side: "BUY" }),
  prop(13, "politics_buy", "Politics Buy Flow", "Politics buys.", { mode: "category_follow", categoryHint: "politics", side: "BUY" }),
  prop(14, "newsy", "Newsy Keywords", "Election/fed/war keywords.", { mode: "keyword_tape" }),
  prop(15, "stale_mid", "Stale Mid", "Buy mid after quiet.", { mode: "mid_band", lo: 0.45, hi: 0.55 }),
  prop(16, "round_fade", "Round Number Fade", "Fade 0.50/0.75 magnets.", { mode: "round_fade" }),
  prop(17, "break_50", "Break 50 Momentum", "Follow crosses near 0.50.", { mode: "break_50" }),
  prop(18, "mr_10c", "10¢ Mean Revert", "Fade 10¢ jumps.", { mode: "mean_revert", jump: 0.1 }),
  prop(19, "mom_10c", "10¢ Momentum", "Follow 10¢ jumps.", { mode: "momentum_jump", jump: 0.1 }),
  prop(20, "thin_skip", "Min Size Filter", "Only size≥50.", { mode: "min_size", minSize: 50 }),
  prop(21, "micro", "Micro Scalp Band", "0.48–0.52 buys.", { mode: "micro_band", lo: 0.48, hi: 0.52 }),
  prop(22, "end_fav", "Endgame Favorite", "Buy >0.85.", { mode: "endgame_favorite", favorite: 0.85 }),
  prop(23, "end_fade", "Endgame Overpay Fade", "Fade 0.90–0.97 tiny size.", { mode: "endgame_fade" }),
  prop(24, "sell_str", "Sell Strength", "Sell into buys >0.70.", { mode: "sell_strength", thr: 0.7 }),
  prop(25, "buy_weak", "Buy Weakness", "Buy ≤0.30.", { mode: "buy_weakness", thr: 0.3 }),
  prop(26, "inv_bal", "Inventory Balance", "Flatten skew.", { mode: "inventory_balance" }),
  prop(27, "single", "Single Position Focus", "Max one market.", { mode: "single_focus" }),
  prop(28, "max3", "Max Three Books", "Cap 3 markets.", { mode: "max_books", maxBooks: 3 }),
  prop(29, "fresh_tape", "Rotate Fresh Tape", "Newest eligible trade.", { mode: "newest_trade" }),
  prop(30, "ignore_crypto", "Ignore Crypto Shorts", "Skip up/down crypto.", { mode: "ignore_crypto" }),
  prop(31, "only_crypto", "Only Crypto Shorts", "Only crypto shorts.", { mode: "only_crypto" }),
  prop(32, "anchor", "Anchor 40–60", "Trade mid band.", { mode: "mid_band", lo: 0.4, hi: 0.6 }),
  prop(33, "batch_maj", "High Activity Follow", "Batch majority side.", { mode: "batch_majority" }),
  prop(34, "batch_min", "Contrarian Batch", "Batch minority side.", { mode: "batch_minority" }),
  prop(35, "whale2k", "Whale ≥$2k", "Mirror size≥2000.", { mode: "min_size_follow", minSize: 2000 }),
  prop(36, "retail25", "Retail ≤$25", "Only tiny prints.", { mode: "max_size", maxSize: 25 }),
  prop(37, "yes_bias", "YES Outcome Bias", "Prefer Yes/Up.", { mode: "outcome_bias", prefer: "yes" }),
  prop(38, "no_bias", "NO Outcome Bias", "Prefer No/Down.", { mode: "outcome_bias", prefer: "no" }),
  prop(39, "tp", "Take Profit Proxy", "Trim +20% winners.", { mode: "take_profit", tp: 0.2 }),
  prop(40, "sl", "Stop Loss Proxy", "Cut −20% losers.", { mode: "stop_loss", sl: 0.2 }),
  prop(41, "hold_win", "Hold Winners", "Only add, rarely sell winners.", { mode: "hold_winners" }),
  prop(42, "first_print", "Opening Drive", "First print follow.", { mode: "first_print_follow" }),
  prop(43, "last_print", "Closing Drive", "Last print follow.", { mode: "last_print_follow" }),
  prop(44, "range_follow", "Vol Expand Follow", "Wide range → follow.", { mode: "range_follow" }),
  prop(45, "range_fade", "Vol Contract Fade", "Tight range → fade.", { mode: "range_fade" }),
  prop(46, "ctrl_rand", "Random Control", "Random eligible tape.", { mode: "random" }),
  prop(47, "ctrl_buy", "Always Buy Control", "Buy eligible prints.", { mode: "always_buy" }),
  prop(48, "ctrl_sell", "Always Sell Control", "Sell when possible.", { mode: "always_sell" }),
  prop(49, "favorite_longshot", "Classic FLB", "Buy favorites & fade longshots combo filter.", { mode: "buy_favorite", favorite: 0.8 }),
  prop(50, "sum_proxy", "Certainty Avoidance", "Avoid >0.95 grinders.", { mode: "skip_extreme", lo: 0.05, hi: 0.95 }),
];

export const ALL_STRATEGIES: StrategyDef[] = [
  ...WALLET_STRATEGIES,
  ...PROP_STRATEGIES,
];

export function getStrategy(id: string) {
  return ALL_STRATEGIES.find((s) => s.id === id);
}
